version: '3.8'

services:
  redis:
    image: redis:8.0
    container_name: be-mentora-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --loglevel notice
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      - REDIS_REPLICATION_MODE=master
    # networks:
    # - mentora-network

volumes:
  redis_data:
    driver: local


