spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true

#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true

#openapi:
#  service:
#    api-docs: backend-service
#    title: Backend Service API Document
#    version: 1.0.0
#    server: http://localhost:${server.port}

#jwt:
#  secretKey: 123@abc456
#  expiryMinutes: 1
#  expiryDays: 14
#  accessKey: 9d65fa89ca005c494febd286b2137e3a39a864a2d822633d2819e39a56c40a91
#  refreshKey: 89e795a0d5084cb24c0e5021b8a0c9bca906c3542f89c4599e7a69602444fede
