server:
  port: 9090

spring:
  devtools:
    add-properties: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      database: 0

  cache:
    type: redis
    redis:
      time-to-live: 15m
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "mentora:"

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
      access-token-expiration: 3600000
      refresh-token-expiration: 604800000