server:
  port: 9090

spring:
  devtools:
    add-properties: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      database: 0

  cache:
    type: redis
    redis:
      time-to-live: 15m
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "mentora:"

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      accessTokenExpiration: 3600000
      refreshTokenExpiration: 604800000
      cookie:
        secure: true

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION:ap-southeast-1}
    bucket-name: ${AWS_S3_BUCKET:mentora-course-videos}


app:
  video:
    max-size: 2147483648  # 2GB in bytes
    allowed-types:
      - video/mp4
      - video/quicktime
      - video/x-msvideo
      - video/x-flv
      - video/webm
    storage-path: ${VIDEO_STORAGE_PATH:videos}